// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ZeajXVL8QRs-41FzcIFRi-a_PrZ-Sgg',
    appId: '1:122691962546:web:c201896d2d9643cf846bab',
    messagingSenderId: '122691962546',
    projectId: 'prueba1-558af',
    authDomain: 'prueba1-558af.firebaseapp.com',
    storageBucket: 'prueba1-558af.appspot.com',
    measurementId: 'G-3RXFW94PE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbVxMuxL7Sr0ecK9zruCejaaI5OshvEsI',
    appId: '1:122691962546:android:c252b9a8293d8aac846bab',
    messagingSenderId: '122691962546',
    projectId: 'prueba1-558af',
    storageBucket: 'prueba1-558af.appspot.com',
  );
}
